name: Run Telegram Bot with Polling

on:
  workflow_dispatch:
  schedule:
    # هر 10 دقیقه بررسی کند
    - cron: '*/10 * * * *'

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: telegram-bot-polling
  cancel-in-progress: false

jobs:
  run-telegram-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # محدودیت زمان
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: 🐍 Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: 🔧 Configure environment
      run: |
        echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $GITHUB_ENV
        echo "TELEGRAM_ADMIN_USERS=6563143907" >> $GITHUB_ENV
    
    - name: 🤖 Test Bot Connection
      run: |
        echo "🤖 Testing bot connection..."
        python -c "
        import asyncio
        from telegram_bot_enhanced import EnhancedTelegramBot
        
        async def test():
            bot = EnhancedTelegramBot('${{ secrets.TELEGRAM_BOT_TOKEN }}')
            info = await bot.get_bot_info()
            print(f'✅ Bot: {info.get(\"first_name\")} (@{info.get(\"username\")})')
            print(f'✅ Admin users: {list(bot.admin_users)}')
        
        asyncio.run(test())
        "
    
    - name: 📱 Run Telegram Bot (Polling)
      run: |
        echo "📱 Starting Telegram Bot with polling..."
        timeout 50m python telegram_polling_bot.py || true
    
    - name: 📊 Generate Status Report
      run: |
        echo "📊 Generating status report..."
        cat > subscriptions/bot_status.json << EOF
        {
          "bot_name": "onix",
          "bot_username": "@onixdev_bot",
          "bot_id": "8474552244",
          "admin_users": [6563143907],
          "status": "polling_active",
          "last_run": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "github_repo": "https://github.com/AhmadAkd/Onix-V2Ray-Collector",
          "polling_interval": "2_seconds",
          "collection_interval": "30_minutes",
          "commands": {
            "start": "شروع کار با ربات",
            "help": "راهنمای استفاده",
            "stats": "آمار کلی سیستم",
            "configs": "دریافت کانفیگ‌ها",
            "admin": "دستورات مدیریتی (فقط ادمین)"
          }
        }
        EOF
    
    - name: 📝 Update README
      run: |
        echo "📝 Updating README with polling info..."
        cat >> README.md << 'EOF'
        
        ## 🤖 Telegram Bot (Polling Mode)
        
        ### 📱 **ربات تلگرام**
        
        - **نام**: onix
        - **Username**: [@onixdev_bot](https://t.me/onixdev_bot)
        - **Bot ID**: 8474552244
        - **وضعیت**: ✅ فعال با Polling
        - **جمع‌آوری**: ✅ هر 30 دقیقه
        
        ### 👑 **ادمین**
        
        - **User ID**: 6563143907
        - **Username**: @Deltamax
        - **نام**: samurai
        
        ### 📱 **دستورات**
        
        | دستور | توضیح |
        |-------|-------|
        | `/start` | شروع کار با ربات |
        | `/help` | راهنمای استفاده |
        | `/stats` | آمار کلی سیستم |
        | `/configs` | دریافت کانفیگ‌ها |
        | `/admin` | دستورات مدیریتی (فقط ادمین) |
        
        ### 🔧 **دستورات ادمین**
        
        | دستور | توضیح |
        |-------|-------|
        | `/admin` | منوی ادمین |
        | `/admin stats` | آمار تفصیلی |
        | `/admin users` | لیست کاربران |
        | `/admin broadcast` | ارسال پیام به همه |
        
        ### 🔄 **جمع‌آوری خودکار**
        
        - **فاصله**: هر 30 دقیقه
        - **منابع**: کانال‌های تلگرام
        - **پروتکل‌ها**: VMess, VLESS, Trojan, SS, SSR, Hysteria
        - **کشورها**: 25+ کشور
        - **گزارش**: ارسال به ادمین
        
        EOF
    
    - name: 📤 Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "🤖 Update Telegram Bot status (Polling Mode)" || exit 0
        git push
