name: Security Scanning

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday

jobs:
  dependency-check:
    name: Dependency Security Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install safety
        run: pip install safety
      
      - name: Check dependencies
        run: |
          echo "🔍 Checking dependencies for vulnerabilities..."
          safety check --file requirements.txt --output text || true
          echo "✅ Dependency check completed"
  
  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install tools
        run: |
          pip install bandit flake8 pylint
      
      - name: Run Bandit (security)
        run: |
          echo "🔒 Running security analysis..."
          bandit -r . -f txt || true
      
      - name: Run Flake8 (style)
        run: |
          echo "📝 Running style check..."
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
  
  secret-scanning:
    name: Secret Scanning
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}

